tunnel: c8e67b13-2249-4281-8170-7744ff8fdfa2
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: helius.sarislabs.com
    service: http://helius-tracker:8080
  - service: http_status:404
